; MODO GRÁFICO
ORG 0100H

MOV AH, 0
MOV AL, 13H      ; CONFIGURAR MODO 320x200 PX, 256 COLORES
INT 10H

MOV AH, 0CH
MOV AL, 00H      ; CONFIGURA PARA UN SOLO PIXEL COLOR NEGRO
MOV CX, 0h       ; COORDENADA DE COLUMNA
MOV DX, 0h       ; COORDENADA DEL RENGLÓN
INT 10H

LINEA:
    INC AL       ; CAMBIA LOS COLORES
    INC DX       ; INCREMENTO COORDENADA EN Y
    INC CX       ; INCREMENTO COORDENADA EN X
    INT 10H      ; SETEA EL COLOR DEL PIXEL
    CMP CX, 100  ; VALOR MÁXIMO
    JNE LINEA    ; BRINCA SI NO ES CERO

LINEA2:
    DEC AL       ; CAMBIA LOS COLORES
    DEC DX       ; INCREMENTO COORDENADA
    INT 10H      ; SETEA EL COLOR DEL PIXEL
    CMP DX, 0  ; VALOR MÁXIMO
    JNE LINEA2    ; BRINCA SI NO ES CERO

LINEA3:
    INC AL       ; CAMBIA LOS COLORES
    DEC CX       ; INCREMENTO COORDENADA
    INT 10H      ; SETEA EL COLOR DEL PIXEL
    CMP CX, 0  ; VALOR MÁXIMO
    JNE LINEA3    ; BRINCA SI NO ES CERO


RET
